Update build_rpm script to push package to OBS
Added option '-o' to build script so that the package can
be pushed to the OpenSUSE build service.

Signed-off-by: Hannes Reinecke <hare@suse.de>

diff --git a/rpm/build_rpm b/rpm/build_rpm
--- a/rpm/build_rpm
+++ b/rpm/build_rpm
@@ -6,11 +6,15 @@
 RPM="multipath-tools"
 BRANCH="sles11-sp1"
 BASEVER="0.4.8"
-DESTDIR="/tmp/$RPM"
+DESTDIR=
 uncommitted_changes=0
 
 while [ $# -gt 0 ] ; do
     case "$1" in
+	-c|--clean)
+	    remove_destdir=1;
+	    shift;
+	    ;;
         -d)
             DESTDIR=$2;
             shift 2;
@@ -27,6 +31,10 @@ while [ $# -gt 0 ] ; do
             BRANCH=${1##*=};
             shift;
             ;;
+	-o|--use-osc)
+	    use_osc=1;
+	    shift;
+	    ;;
         -f|--force)
             force=1;
 	    update=;
@@ -42,7 +50,7 @@ while [ $# -gt 0 ] ; do
             shift;
             ;;
         *)
-            echo "Usage: build_rpm [-f|-u] [-d dir|--destdir=DIR] " \
+            echo "Usage: build_rpm [-c|-f|-o|-u] [-d dir|--destdir=DIR] " \
                  "[-b BRANCH|--branch=BRANCH] [--uncommitted-changes]"
             exit 1;
             ;;
@@ -71,6 +79,12 @@ if [ -d "$DESTDIR" ] ; then
             exit 1
         fi
     fi
+else
+    DESTDIR=$(mktemp -d --tmpdir $RPM-XXXXXXXX)
+    if [ ! -d "$DESTDIR" ] ; then
+	echo "Cannot create directory $DESTDIR"
+	exit 1
+    fi
 fi
 
 if ! git branch | grep -q "$BRANCH" ; then
@@ -80,9 +94,11 @@ else
     echo "Checking out from $BRANCH"
 fi
 
-if [ -z "$update" ] && ! mkdir $DESTDIR ; then
-    echo "Cannot create directory $DESTDIR"
-    exit 1
+if [ -n "$use_osc" ] ; then
+    pushd $DESTDIR
+    osc co --current-dir home:hreinecke:SLES11-SP1 multipath-tools
+    DESTDIR="${DESTDIR}/multipath-tools"
+    popd
 fi
 
 git archive --format=tar --prefix=$RPM-$VERSION/ "$VERSION" \
@@ -109,3 +125,14 @@ Patch1:\t\t$patchname" $DESTDIR/rpm/$RPM.spec
 fi
 
 echo "$RPM src rpm copied to $DESTDIR"
+
+if [ -n "$use_osc" ] ; then
+    pushd $DESTDIR
+    osc ar
+    osc ci --message="Checked in from git branch $BRANCH"
+    popd
+fi
+
+if [ -n "$remove_destdir" ] ; then
+    rm -rf $DESTDIR
+fi
